/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./src/components/CommonFooter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ModelViewer: typeof import('./src/components/ModelViewer.vue')['default']
    MotionExample: typeof import('./src/components/MotionExample.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RipplingText: typeof import('./src/components/RipplingText.vue')['default']
    ScrollingBar: typeof import('./src/components/ScrollingBar.vue')['default']
  }
}
